repos:
	- repo: https://github.com/charliermarsh/ruff-pre-commit
		rev: v0.24.0
		hooks:
			- id: ruff

	- repo: https://github.com/psf/black
		rev: 23.9.1
		hooks:
			- id: black
				language_version: python3
+repos:
+  - repo: https://github.com/charliermarsh/ruff-pre-commit
+    rev: v0.24.0
+    hooks:
+      - id: ruff
+
+  - repo: https://github.com/psf/black
+    rev: 23.9.1
+    hooks:
+      - id: black
+        language_version: python3
