version: '3.9'

services:
  db:
    image: postgres:15
    container_name: velkilist-db
    restart: always
    environment:
      POSTGRES_DB: velkilist_db
      POSTGRES_USER: velki_user
      POSTGRES_PASSWORD: velki_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .                        # ✅ Dockerfile use হবে
    container_name: velkilist-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles 
      - media_volume:/app/config/media  
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: