# Generated by Django 5.2.7 on 2025-10-22 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Casino categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CasinoProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CasinoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('provider_game_id', models.CharField(db_index=True, max_length=100)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('rtp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volatility', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='games', to='casino.casinocategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='casino.casinoprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CasinoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_session_id', models.CharField(blank=True, max_length=100)),
                ('launch_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='casino.casinogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='casinogame',
            index=models.Index(fields=['name'], name='casino_casi_name_7590e4_idx'),
        ),
        migrations.AddIndex(
            model_name='casinogame',
            index=models.Index(fields=['slug'], name='casino_casi_slug_e1092e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casinogame',
            unique_together={('provider', 'provider_game_id')},
        ),
    ]
