# Generated by Django 5.2.7 on 2025-10-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinoprovider',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
