# Generated by Django 5.2.7 on 2025-10-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/')),
                ('country', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, help_text='ID from external API', max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='sports.category')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('closed', 'Closed for Betting'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('score_home', models.IntegerField(blank=True, null=True)),
                ('score_away', models.IntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='sports.league')),
            ],
            options={
                'ordering': ['start_time', 'league__name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('1x2', '1X2'), ('ou', 'Over/Under'), ('gg', 'Both Teams to Score'), ('cs', 'Correct Score'), ('ht', 'Half Time'), ('dc', 'Double Chance')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('specifier', models.JSONField(blank=True, help_text='Additional parameters like handicap/total', null=True)),
                ('priority', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='sports.game')),
            ],
            options={
                'ordering': ['priority', 'market_type'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('american_odds', models.IntegerField(blank=True, null=True)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('cashout', 'Cash Out')], default='active', max_length=20)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='sports.market')),
            ],
            options={
                'ordering': ['market', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('leagues', models.ManyToManyField(related_name='teams', to='sports.league')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='sports.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='sports.team'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'market_type'], name='sports_mark_status_6e70c7_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['external_id'], name='sports_mark_externa_e752dd_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['status'], name='sports_sele_status_9e3f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['external_id'], name='sports_sele_externa_fc3904_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'start_time'], name='sports_game_status_aab06c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['external_id'], name='sports_game_externa_d2d48c_idx'),
        ),
    ]
