# Generated by Django 5.2.7 on 2025-10-21 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_recon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='flow',
            field=models.CharField(choices=[('server', 'Server'), ('redirect', 'Redirect')], default='server', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='provider',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='display_number',
            field=models.CharField(help_text='Number shown to users for cash transfers', max_length=64),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='provider_account',
            field=models.CharField(blank=True, help_text='User provided number / account', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount_cents', models.BigIntegerField()),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('our_status', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatched', 'Mismatched'), ('missing', 'Missing'), ('extra', 'Extra')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.reconciliationbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transactions', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('mismatched_count', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('extra_count', models.IntegerField(default=0)),
                ('total_amount_cents', models.BigIntegerField(default=0)),
                ('mismatched_amount_cents', models.BigIntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.reconciliationbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='reconciliationbatch',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='payments_re_provide_438f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['batch', 'status', 'transaction_id'], name='payments_re_batch_i_6a795a_idx'),
        ),
    ]
