# Generated by Django 5.2.7 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reserved_balance_cents',
            field=models.BigIntegerField(default=0),
        ),
    ]
