# Generated by Django 5.2.7 on 2025-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_reserved_balance_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet', 'Bet'), ('hold', 'Hold'), ('commission', 'Commission'), ('win', 'Win'), ('refund', 'Refund')], max_length=10),
        ),
    ]
