# Generated by Django 5.2.7 on 2025-10-21 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake_cents', models.BigIntegerField()),
                ('potential_win_cents', models.BigIntegerField()),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='placed', max_length=10)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=128)),
                ('market', models.CharField(max_length=128)),
                ('selection', models.CharField(max_length=128)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=9)),
                ('stake_cents', models.BigIntegerField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bets.bet')),
            ],
        ),
    ]
