# Generated by Django 5.2.7 on 2025-10-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_bn', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_bn', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VelkiList', max_length=120)),
                ('default_locale', models.CharField(default='en', max_length=5)),
                ('ga_measurement_id', models.CharField(blank=True, max_length=32, null=True)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
