# Generated by Django 5.2.7 on 2025-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='robots_txt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_default_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_default_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
