# Generated by Django 5.2.7 on 2025-10-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sitesetting_custom_css_sitesetting_homepage_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs_enabled', models.BooleanField(default=True)),
                ('sports_fetch_schedule', models.CharField(blank=True, default='*/5 * * * *', max_length=50)),
                ('odds_fetch_schedule', models.CharField(blank=True, default='*/10 * * * *', max_length=50)),
                ('backup_schedule', models.CharField(blank=True, default='0 2 * * *', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtensionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sportsbook_enabled', models.BooleanField(default=True)),
                ('casino_enabled', models.BooleanField(default=True)),
                ('realtime_enabled', models.BooleanField(default=True)),
                ('reports_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('supported_languages', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, default='manual', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_title', models.CharField(blank=True, default='', max_length=200)),
                ('default_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLoginSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_enabled', models.BooleanField(default=False)),
                ('google_client_id', models.CharField(blank=True, default='', max_length=200)),
                ('google_client_secret', models.CharField(blank=True, default='', max_length=200)),
                ('facebook_enabled', models.BooleanField(default=False)),
                ('facebook_app_id', models.CharField(blank=True, default='', max_length=200)),
                ('facebook_app_secret', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
