# Generated by Django 5.2.7 on 2025-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_cronjobsetting_extensionsetting_languagesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRCookieSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('title', models.CharField(default='We value your privacy', max_length=120)),
                ('message', models.TextField(blank=True, default='We use cookies to enhance your experience. By continuing, you agree to our cookie policy.')),
                ('policy_url', models.CharField(blank=True, default='/pages/privacy-policy', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
