name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: velkilist_db
          POSTGRES_USER: velki_user
          POSTGRES_PASSWORD: velki_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ job.services.postgres.env.POSTGRES_USER }}" \
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff
        pip install black
        pip install pre-commit
    - name: Lint (ruff)
      run: |
        ruff check .
    - name: Format check (black)
      run: |
        black --check .
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files || true
    - name: Run migrations
      env:
        DB_NAME: velkilist_db
        DB_USER: velki_user
        DB_PASSWORD: velki_pass
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
    - name: Run tests
      run: |
        python manage.py test --verbosity=2
