# Generated by Django 5.2.7 on 2025-10-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_default_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_73c1f5_idx',
            old_name='inapp_recipient_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_notific_219496_idx',
            old_name='notif_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_recipie_3db547_idx',
            old_name='notif_recipient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_phone_n_27ca6c_idx',
            old_name='notif_phone_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_email_9adaf3_idx',
            old_name='notif_email_created_idx',
        ),
    ]
